version: '3.9'

services:
  flask:
    build:
      dockerfile: ./docker/flask.dockerfile
      context: ./
    ports:
      - 8000:8000
    volumes:
      - ./app_flask:/app
    # depends_on:
    #   - db
    # environment:
    #   - DB_HOST=db
    #   - DB_PORT=5432

  # db:
  #   build:
  #     dockerfile: ./docker/postgres.dockerfile
  #     context: ./
  #   volumes:
  #     - ./data:/var/lib/postgresql/data
  #   ports:
  #     - 5432:5432

  api:
    image: insectatorious/word2vec-api

